# Master run_mode
run_mode:
  fem: TRUE # Boolean for whether to run the fem
  model: TRUE # Boolean for whether to run the model

# Fem config
fem_config:

  io:
    snapshot_path: "runs/traintune_original/fixed_sched/snapshot.npz"
    plot_path: "runs/traintune_original/fixed_sched/fem_plot.png"


# Network config
net_config:

  loss:
    weight_schedule:
      - [1.0, 1.0, 5000]

  data:
    snapshot_path: "runs/traintune_original/fixed_sched/snapshot.npz"

  export:
    mode: "online"
    wandb_entity: "Hypersonics"
    wandb_project: "large-scale-runs"
    wandb_name: "traintune_original/fixed_sched"
    local_log_path: "runs/traintune_original/fixed_sched/model_log.txt"
    model_save_path: "runs/traintune_original/fixed_sched/model.pt"
    plot_comp_path: "runs/traintune_original/fixed_sched/model_comp_plot.png"



